

from PyQt5.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PyQt5.QtWidgets import *

app = QApplication([]) ## a REQUIREMENT for all applications to have one QApplication initialised
app.setStyle('Fusion')
window = QDialog() # creates the window itself

class Add_Client_Window(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(948, 305)
        Dialog.setMinimumSize(QSize(948, 305))
        Dialog.setMaximumSize(QSize(948, 305))
        self.buttonBox = QDialogButtonBox(Dialog)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(495, 247, 341, 32))
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.lineEdit = QLineEdit(Dialog)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(201, 46, 194, 22))
        self.lineEdit.setStyleSheet(u"font: 9pt \"MS Shell Dlg 2\";")
        self.label = QLabel(Dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(41, 46, 100, 16))
        self.label.setStyleSheet(u"font: 10pt \"MS Shell Dlg 2\";")
        self.label_2 = QLabel(Dialog)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(41, 76, 108, 19))
        self.label_2.setStyleSheet(u"font: 10pt \"MS Shell Dlg 2\";")
        self.label_3 = QLabel(Dialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(42, 106, 121, 16))
        self.label_3.setStyleSheet(u"font: 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_2 = QLineEdit(Dialog)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(201, 76, 194, 22))
        self.lineEdit_3 = QLineEdit(Dialog)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(201, 106, 194, 22))
        self.lineEdit_4 = QLineEdit(Dialog)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(201, 136, 193, 22))
        self.lineEdit_5 = QLineEdit(Dialog)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(201, 171, 192, 22))
        self.lineEdit_6 = QLineEdit(Dialog)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(200, 206, 193, 22))
        self.label_4 = QLabel(Dialog)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(41, 136, 100, 16))
        self.label_4.setStyleSheet(u"font: 10pt \"MS Shell Dlg 2\";")
        self.label_5 = QLabel(Dialog)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 200, 100, 16))
        self.label_5.setStyleSheet(u"font: 10pt \"MS Shell Dlg 2\";")
        self.label_6 = QLabel(Dialog)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(41, 170, 100, 16))
        self.label_6.setStyleSheet(u"font: 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_7 = QLineEdit(Dialog)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(629, 106, 201, 22))
        self.lineEdit_8 = QLineEdit(Dialog)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(629, 171, 204, 22))
        self.label_7 = QLabel(Dialog)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(469, 136, 103, 17))
        self.label_7.setStyleSheet(u"font: 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_9 = QLineEdit(Dialog)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(629, 76, 203, 22))
        self.lineEdit_10 = QLineEdit(Dialog)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(629, 136, 203, 22))
        self.label_9 = QLabel(Dialog)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(470, 106, 100, 16))
        self.label_9.setStyleSheet(u"font: 10pt \"MS Shell Dlg 2\";")
        self.label_10 = QLabel(Dialog)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(469, 170, 100, 16))
        self.label_10.setStyleSheet(u"font: 10pt \"MS Shell Dlg 2\";")
        self.label_11 = QLabel(Dialog)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(469, 46, 100, 16))
        self.label_11.setStyleSheet(u"font: 10pt \"MS Shell Dlg 2\";")
        self.label_12 = QLabel(Dialog)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(469, 76, 100, 16))
        self.label_12.setStyleSheet(u"font: 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_12 = QLineEdit(Dialog)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(629, 46, 204, 22))

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.lineEdit.setText("")
        self.label.setText(QCoreApplication.translate("Dialog", u"Client Name", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Company", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Phone Number", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Extension", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Website", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"Email", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"County", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"City", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"Postcode", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"Address 1", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"Address 2", None))
    # retranslateUi
def main():
   # db = sqlite3.connect('example.db') #load in the database
    Mainwindow = Add_Client_Window()
    Mainwindow.setupUi(window)
    window.show()
    app.exec_()

if __name__ == "__main__":
    main()
